services:
  - name: docker:dind
    command: ["--tls=false"]
  - redis:latest

variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=poc/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress

image: maven:latest
cache:
  paths:
    - poc/.m2/repository

build-and-test:
  stage: test
  script:
    - cd poc
    - 'mvn $MAVEN_CLI_OPTS verify'